// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import {
  getDevelopmentDatabaseUrl,
  getDevelopmentShadowDatabaseUrl,
} from "./lib/database/database-env";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDevelopmentDatabaseUrl(),
    shadowDatabaseUrl: getDevelopmentShadowDatabaseUrl(),
  },
});
