ALTER TABLE "Order"
ADD COLUMN "client_order_code" TEXT,
ADD COLUMN "note" TEXT,
ADD COLUMN "required_note" TEXT,
ADD COLUMN "payment_type_id" INTEGER,
ADD COLUMN "from_name" TEXT,
ADD COLUMN "from_phone" TEXT,
ADD COLUMN "from_address" TEXT,
ADD COLUMN "from_ward_name" TEXT,
ADD COLUMN "from_district_name" TEXT,
ADD COLUMN "from_province_name" TEXT,
ADD COLUMN "return_phone" TEXT,
ADD COLUMN "return_address" TEXT,
ADD COLUMN "return_district_id" INTEGER,
ADD COLUMN "return_ward_code" TEXT,
ADD COLUMN "to_ward_code" TEXT,
ADD COLUMN "to_district_id" INTEGER,
ADD COLUMN "cod_amount" DECIMAL(12, 2) NOT NULL DEFAULT 0,
ADD COLUMN "content" TEXT,
ADD COLUMN "weight" INTEGER,
ADD COLUMN "length" INTEGER,
ADD COLUMN "width" INTEGER,
ADD COLUMN "height" INTEGER,
ADD COLUMN "insurance_value" DECIMAL(12, 2) NOT NULL DEFAULT 0,
ADD COLUMN "service_id" INTEGER,
ADD COLUMN "service_type_id" INTEGER,
ADD COLUMN "pick_station_id" INTEGER,
ADD COLUMN "deliver_station_id" INTEGER,
ADD COLUMN "coupon" TEXT,
ADD COLUMN "pick_shift" INTEGER[] DEFAULT ARRAY[]::INTEGER[];

ALTER TABLE "OrderItem"
ADD COLUMN "item_weight" INTEGER,
ADD COLUMN "item_length" INTEGER,
ADD COLUMN "item_width" INTEGER,
ADD COLUMN "item_height" INTEGER,
ADD COLUMN "category_level1" TEXT;
